[package]
name = "unique-id-generation"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "02-unique-id-generation"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
